# Generated by Django 6.0.1 on 2026-02-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='location',
            field=models.CharField(blank=True, help_text='Google Maps link or landmark', max_length=255),
        ),
        migrations.AddField(
            model_name='pg',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pg_photos/'),
        ),
    ]
